### ISSUE TITLE
Several issues... (gravity, light condition of objects, and missing rigid_obj_mgr)

### ISSUE THREAD

**Issue by bareblackfoot** [facebookresearch/habitat-sim#1252]
I tried to change the gravity of a scene to vector3(0,-9.8,0), but it does not work :(
It always says that the gravity is Vector3(0,0,0).
When I tested on the google colab, set_gravity() works, but not on my server computers.
I couldn't succeed installing with anaconda version since the libEGL is not found when I install habitat with anaconda.
I installed a habitat-sim 0.1.17 with python setup.py, specifying the directory of the libEGL.
When I installed stable and master versions, using bullet, with-cuda, headless, both versions (stable, master) didn't work.

Secondly, when I add objects to the scene, the color of objects is almost black (it only happens on habitat-sim 0.1.17, not 0.1.16).
We found out that setting requires_lighting: false on objects.json, add_object(light_setup_key="no_lights"), scene_light_setup="no_lights" works. is it right?

Third, I couldn't get rigid_obj_mgr which is available on the google-colab installation.
How can I get rigid_obj_mgr?

**Comment by aclegg3** [comment]
> It always says that the gravity is Vector3(0,0,0).

This indicates that Bullet support is not correctly configured during install. There should also be a message on console to that effect.

> when I add objects to the scene, the color of objects is almost black ...  on habitat-sim 0.1.17 ... setting requires_lighting: false ... add_object(light_setup_key="no_lights") ... works. 

Yes, the example objects are scans from the YCB dataset. Their default materials don't play well with the current version of the PBR shader in Habitat-sim. As you noted the color comes out very dark. Because they are scans they end up looking pretty good flat shaded. 

> I couldn't get rigid_obj_mgr

This is a very new feature on the master branch only, so you'll need to use the most recent builds. Either master branch installed from source, or the [nightly conda builds](https://anaconda.org/aihabitat-nightly).
