### ISSUE TITLE
Identify point on scan and find closest vertex in .obj file

### ISSUE THREAD

**Issue by arjung128** [facebookresearch/habitat-sim#1666]
## Habitat-Sim version
v0.2.1

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest [release version](https://github.com/facebookresearch/habitat-sim/releases) of Habitat-Sim? Your question may already be addressed in the latest version. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Main branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-sim/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help
Is it possible to use the simulator to select a point on the scan and then get the closest vertex (to this selected point) in the .obj file of the scan?

**Comment by aclegg3** [comment]
Hey @arjung128,

I don't think this is easy in the `main` branch because we don't have any accessors for mesh geometry and topology exposed. 
You can query collision points with a scene via camera ray-casting from pixels with the depth buffer, or using Bullet physics integration. However, you'd need to implement a way to access the ground truth scene mesh data (like [this PR](https://github.com/facebookresearch/habitat-sim/pull/1149) for example).
