### ISSUE TITLE
Can't navigate in apratment_1 scene

### ISSUE THREAD

**Issue by VladimirYugay** [facebookresearch/habitat-sim#2141]
Hey there,

For some reason, when the  apartment_0 scene is loaded in the viewer, I can't leave the starting room - the agent just refuses to go back. It seems like everything outside the starting room is not navigable. 

I don't see this behavior in any other scenes. 

The command I use to run the viewer:

`python examples/viewer.py --scene ~/datasets/Replica/apartment_2/habitat/mesh_semantic.ply`

**Comment by aclegg3** [comment]
@VladimirYugay it is always possible that the navmesh for a scene is incomplete. Often it is broken by holes in the floor, for example. You can press `'n'` to visualize the navmesh and `ALT+'n'` to resample the agent's position in order to teleport to another location on the navmesh and get yourself unstuck.
