### ISSUE TITLE
Error while running examples/interactive_play.py --never-end

### ISSUE THREAD

**Issue by AbhiramRV** [facebookresearch/habitat-sim#2184]
I am trying to run examples scripts but receiving error that path to data is not available
![Screenshot from 2023-08-12 19-56-15](https://github.com/facebookresearch/habitat-sim/assets/42892177/0455b0b8-d6ce-418a-92b5-e400a2778254)

**Comment by aclegg3** [comment]
Hey @AbhiramRV 
This script is actually a habitat-lab feature and unrelated to habitat-sim. I'll close this issue.

However, it seems to me that you have a version mismatch issue. This error indicates that you don't have the robot assets. https://huggingface.co/datasets/ai-habitat/hab_fetch is current.

As noted in [this dataset comment](https://huggingface.co/datasets/ai-habitat/ReplicaCAD_dataset/discussions/1), the urdf in question should not be referenced in ReplicaCAD, since that is no longer the correct path. This indicates to me that your code is looking for a stale version of the asset (before v0.2.5).

If you use an older version of the downloader in habitat-sim you should get the correct fetch asset. Otherwise upgrade everything to the newest version. If you still have trouble, feel free to open a new issue on habitat-lab. Thanks!
