### ISSUE TITLE
Unable to download hssd dataset

### ISSUE THREAD

**Issue by taylorlulu** [facebookresearch/habitat-sim#2254]
When I'm trying to download hssd dataset using the command 
`python -m habitat_sim.utils.datasets_download --uids hssd-hab --data-path data/`
It reported 
`git clone --depth 1 --branch main git@hf.co:datasets/hssd/hssd-hab.git /home/lu/Desktop/embodied_ai/data/versioned_data/hssd-hab
Cloning into '/home/lu/Desktop/embodied_ai/data/versioned_data/hssd-hab'...
/home/lu/.ssh/config: line 6: Bad configuration option: password
/home/lu/.ssh/config: terminating, 1 bad configuration options
fatal: Could not read from remote repository.`
When I open the link with the browser 
![image](https://github.com/facebookresearch/habitat-sim/assets/49311079/8f289bd3-48cc-4731-bdb0-ce473a211341)
How can I download the hssd dataset?

**Comment by Jinghan11** [comment]
The appropriate link is https://huggingface.co/datasets/hssd/hssd-hab.

However, I'm encountering issues when trying to download this dataset. While I can successfully execute the command` git clone https://huggingface.co/datasets/hssd/hssd-hab`, I don't seem to have and don't konw how to get the necessary permissions to use` python -m habitat_sim.utils.datasets_download --uids hssd-hab` for downloading the dataset. This issue could potentially be due to the datasets_download script using SSH instead of HTTPS.

**Comment by taylorlulu** [comment]
@Jinghan11 Yes, I successfully run the `git clone https://huggingface.co/datasets/hssd/hssd-hab` command as well. I agree it may be something wrong with the `habitat_sim.utils.datasets_download`.

**Comment by Jinghan11** [comment]
Have you ever tried running a program related to Habitat-3.0 Multi-Agent Training? I am not sure if this problem is causing the FileNotFoundError when I run `python habitat_baselines/run.py --config-name=social_nav/social_nav.yaml`. I have opened an [issue](https://github.com/facebookresearch/habitat-lab/issues/1677) about this in the habitat-lab repo.

**Comment by taylorlulu** [comment]
@Jinghan11 No I haven't. I'll try it.
