### ISSUE TITLE
ImportError: cannot import name 'ReplayRenderer' from 'habitat_sim' (/usr/local/envs/pvr_habitat/lib/python3.8/site-packages/habitat_sim-0.2.3-py3.8-linux-x86_64.egg/habitat_sim/__init__.py)

### ISSUE THREAD

**Issue by rebecajohn** [facebookresearch/habitat-sim#2300]
PluginManager::Manager::Manager(): none of the plugin search paths in {../lib/magnum/importers, magnum/importers} exists and pluginDirectory was not set, skipping plugin discovery
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    import habitat
  File "/content/habitat-lab/habitat-lab/habitat/__init__.py", line 17, in <module>
    from habitat.core.vector_env import ThreadedVectorEnv, VectorEnv
  File "/content/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 35, in <module>
    from habitat.core.batch_rendering.env_batch_renderer import EnvBatchRenderer
  File "/content/habitat-lab/habitat-lab/habitat/core/batch_rendering/env_batch_renderer.py", line 33, in <module>
    from habitat_sim import ReplayRenderer, ReplayRendererConfiguration
ImportError: cannot import name 'ReplayRenderer' from 'habitat_sim' (/usr/local/envs/pvr_habitat/lib/python3.8/site-packages/habitat_sim-0.2.3-py3.8-linux-x86_64.egg/habitat_sim/__init__.py)

**Comment by aclegg3** [comment]
Hey @rebecajohn, possibly this is a version API mixup. It looks like the issue is origination from habitat-lab importing habitat-sim. Possibly the version of lab you are using is well advanced from sim v0.2.3?

If you need further support on this, please open an issue on habitat-lab and include your lab commit so we can advise on compatibility.
