### ISSUE TITLE
habitat challenge 2022 habitat--version

### ISSUE THREAD

**Issue by ChrisWanghb** [facebookresearch/habitat-sim#2305]
Please tell me the version of habitat-sim and habitat-lab used by habitat challenge 2022 .I am looking forward to your reply!!!

**Comment by aclegg3** [comment]
Hey @ChrisWanghb 

You can typically find a branch named after each challenge year in the repo.
Assuming you are asking after the Habitat navigation challenge 2022 (rather than rearrange challenge 2022)
- https://github.com/facebookresearch/habitat-lab/tree/challenge-2022-branch
- https://github.com/facebookresearch/habitat-sim/tree/challenge-2022-branch

**Comment by aclegg3** [comment]
There is also a conda build for sim still available: https://anaconda.org/aihabitat/habitat-sim-challenge-2022
