### ISSUE TITLE
Incorrect agent state returned

### ISSUE THREAD

**Issue by rakeshshrestha31** [facebookresearch/habitat-sim#4]
## Steps to reproduce

  1. Replace the file [src/esp/gfx/Viewer.cpp](https://github.com/facebookresearch/habitat-sim/blob/master/src/esp/gfx/Viewer.cpp) with the file [Viewer.txt](https://github.com/facebookresearch/habitat-sim/files/2973550/Viewer.txt) (Note: the file extension should be changed to cpp)
  2. Build the project
  3. Run the "viewer" executable on one of the habitat-test-scenes
  4. Rotate the camera view using the arrow keys

## Observed Results
  * The y-rotation computed from the cameraNode_->getRotation() is always zero while the one computed from cameraNode_->getAbsoluteTransformation() is correct. The link below shows the results. This link shows the result: [video](https://drive.google.com/open?id=1MXZKLwcvPzyQSHeC6aoifHSI2sMdCjFS)
   * Similar thing is observed when using the python binding [habitat_sim/simulator.py](https://github.com/facebookresearch/habitat-sim/blob/master/habitat_sim/simulator.py). Steps to reproduce this is not included for brevity, but can be provided if needed.

## Expected Results

  * The two rotations (default rotation and transformation based rotation) should be the same

## Relevant Code

```
  std::cout
    << std::fixed
    << std::setprecision(2)
    << "default rotation: " << cameraNode_->getRotation().toRotationMatrix().eulerAngles(1, 0, 2).transpose() * 180 / M_PI << std::endl
    <<"matrix based rotation: " << quaternion.toRotationMatrix().eulerAngles(1, 0, 2).transpose() * 180 / M_PI << std::endl
    << std::endl;
```
Connection of controls to navmesh is disabled for pure teleoperation
```
if (false) { // pathfinder_->isLoaded()) {
```

**Comment by erikwijmans** [comment]
This is due to how the agent and the camera are related to each-other.  The camera maintains a translation and rotation relative to the agent's body.  When the arrow keys are pressed, this actually rotates the agents body, which in turn rotates the camera, thus the camera's location relative to the agent's body isn't changed.

`getRotation()` returns the rotation of the camera relative to the agent, while `getAbsoluteTransformation()` returns the location of the camera in world coordinates.

It is currently on our list of "todos" to properly expose the camera's location and we will make sure to do that in world coordinates.

You mention a similar issue with `example.py`?  `agent_state.rotation` only captures the rotation of the agent, so if you lookUp or lookDown, this won't be reflected in the agents rotation, but the agents rotation about the +Y axis should be captured by `agent_state.rotation`.

**Comment by rakeshshrestha31** [comment]
Thank you for the explanation. Didn't know that the camera and the agent were related in that way.

And yes, the issue with `example.py` is how you described. Additionally, the agent's vertical translation (along y-axis) is not captured in the python interface.
