### ISSUE TITLE
some question about obstacle detection in Habitat simulator

### ISSUE THREAD

**Issue by UncleMEDM** [facebookresearch/habitat-sim#522]
I found that in some Matterport scene, some place does not seems to have obstable, however, the simulator is not able to get through. For example, I use the ./build/viewer to view the matterport scene 1pXnuDYAj8r.glb. The initial location was located at the balcony, and the agent is not able to get to the living room due to such issue. I think it would be a problem when training an agent. Is there any solution to this?

**Comment by aclegg3** [comment]
Thanks for logging an issue, @UncleMEDM.

This sounds like an issue with the navigation mesh generated from the scene geometry. It is the case that some scenes have holes, hanging geometry, or low doorways which could cause areas which appear clear to be unnavigable. 

You can use the navmesh visualization feature in PR #531 to visualize the issue and see what the problem is. You can also use the `recomputeNavmesh` utility function in 'viewer.cpp' to try custom `NavMeshSettings` for the scene to attempt to remedy the issue.

However, it is possible that the limitation cannot be overcome and specific scenes with problems should be removed from your dataset for training.
