### ISSUE TITLE
phys_scene_config.json file not found

### ISSUE THREAD

**Issue by Mingxiao-Li** [facebookresearch/habitat-sim#827]
## ❓ Questions and Help
Hi, I got the below error, and have found this phys file in this github. Does anyone know where can I download this file ?
 File (./data/default.phys_scene_config.json) not found so new, default physics manager attributes created and registered.

**Comment by jturner65** [comment]
Can you share more information about your habitat-sim installation?

**Comment by Mingxiao-Li** [comment]
Hi. 
I follow the instruction on the github webpage and use conda package to install habitat-sim. The system is Ubuntu. 
I got this error when I try to evaluate the baseline model of VLN-CE model. But then I just found that it is the below error abort the program. 
E1005 14:26:40.204874  5873 StageAttributesManager.cpp:121] StageAttributesManager::registerAttributesTemplateFinalize : Render asset template handle : data/scene_datasets/mp3d/v1/task/mp3d/x8F5xyUWy9e/x8F5xyUWy9e.glb specified in stage template with handle : data/scene_datasets/mp3d/v1/task/mp3d/x8F5xyUWy9e/x8F5xyUWy9e.glb does not correspond to any existing file or primitive render asset.  Aborting. 
Could you kindly inform me how should I solve this error ?

**Comment by Mingxiao-Li** [comment]
Problem solved. Thanks

**Comment by yuanhui-code** [comment]
> Problem solved. Thanks

Hello! I also encountered the same problem, how did you solve it? Thank you!

**Comment by wwtx9** [comment]
Hello, I have encountered the same problem, how did you solve it?

> > Problem solved. Thanks
> 
> Hello! I also encountered the same problem, how did you solve it? Thank you!

**Comment by abstinentcode** [comment]
> 

Hello! I also encountered the same problem, how did you solve it? Thank you!

**Comment by abstinentcode** [comment]
Hello, I also encountered the same problem, how did you solve it? Thank you! @wwtx9 @yuanhui-code @Mingxiao-Li

**Comment by aclegg3** [comment]
@abstinentcode likely you are getting this message because the file [data/default.physics_config.json](https://github.com/facebookresearch/habitat-sim/blob/main/data/default.physics_config.json) needs to be in your data folder or provided during initialization with [SimulatorConfiguration.physics_config_file](https://aihabitat.org/docs/habitat-sim/habitat_sim.sim.SimulatorConfiguration.html#physics_config_file).

If you clone the habitat-sim repo (recommended) and run code from within that directory, this file will be in the correct place. Otherwise you should create this file and manually set the path to it on your system.
