### ISSUE TITLE
Instance Id in semanctic sensor

### ISSUE THREAD

**Issue by krantiparida** [facebookresearch/habitat-sim#945]
## ❓ Questions and Help
Hi,
I got the semantic label using the code below.
instance_id_to_label_id = {int(obj.id.split("_")[-1]): obj.category.index() for obj in scene.objects}
However, I noticed the instance id for the object changes every scene. e.g. the semantic label 'wall' is 129 in one scene whereas it is '134' in another. Is the mapping not consistent?

**Comment by erikwijmans** [comment]
Many different objects (where an object will specified by its instance ID) will have the same semantic category, so a given semantic label cannot map to a single instance ID.  The instance IDs are not consistent across scenes because different scenes have different objects.  So no, the mapping from semantic label to instance ID is not consistent because this is not possible.

**Comment by Skylion007** [comment]
@krantiparida Yeah, you need to rebuilt this mapping for every scene that you load.

**Comment by krantiparida** [comment]
Thanks for the clarification.
